
name: wazo-provd-coredump
namespace: wazocommunication
version: 2.0.0
author: Wazo authors
display_name: wazo-provd Core Dump
min_wazo_version: 24.02
tags:
  - wazo-provd
  - debug
homepage: https://github.com/wazo-communication/wazo-provd-coredump-plugin
